// C ABI boundary. Pointers come from the native host (Swift/C#); validity is their
// responsibility.
#![allow(clippy::not_unsafe_ptr_arg_deref)]

//! The stable C ABI the native UI links (committed `dontspeak.h`, generated by
//! cbindgen). The app is an informational menu-bar + health panel, so this
//! surface is small and HANDLE-FREE (no opaque handle type): read-only probes,
//! the in-process engine lifecycle (start/stop/reload), a few session controls
//! (mute, TTS provider, locale), shared UI constants/formatters/i18n lookups,
//! and the string free. The rich control surface
//! (voice/engine/language/rate/toggles/downloads) lives in DontSpeak.

use std::ffi::{CString, c_char};
use std::panic::{AssertUnwindSafe, catch_unwind};

use crate::{engine, models};

// Every panic reachable from this file's `extern "C"` fns is meant to be caught by
// `guard_val`/`guard_str` below and turned into a safe default — but `catch_unwind` is a
// documented no-op when the crate is compiled with `panic = "abort"` (the process aborts
// before unwinding ever starts), which silently voids this entire safety boundary for
// whatever native app has this staticlib/cdylib loaded in-process. The workspace's
// `release-ffi` profile (rust/Cargo.toml) exists specifically to override the default
// `release` profile's `panic = "abort"` back to `"unwind"` for this crate — every build of
// ds-core as a cdylib/staticlib for a hosting native app MUST use it (see
// apps/macos/build.sh and apps/windows/installer/build-common.ps1). Fail the build loudly
// instead of silently shipping a host process that aborts on any FFI-reachable panic.
#[cfg(panic = "abort")]
compile_error!(
    "ds-core must not be built with panic=\"abort\" -- its extern \"C\" boundary relies on \
     catch_unwind (see guard_val/guard_str below), which is a documented no-op under an abort \
     strategy and would let any panic reachable from an extern \"C\" fn abort the whole hosting \
     process. Build with `cargo build --profile release-ffi -p ds-core` (or any profile with \
     panic=\"unwind\") instead of the default `release` profile."
);

// ── In-process engine host ───────────────────────────────────────────────────
// The lifecycle state lives in [`crate::host`] (the ONE owner, kept out of this boundary so
// a stray second start can't spawn a competing engine); these C entry points are thin
// adapters returning the u8 the committed `dontspeak.h` documents.

/// Start the engine on a background thread if not already running. Returns 1 if
/// it is now running (started or already up), 0 on failure.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_start() -> u8 {
    guard_val(0, || crate::host::engine_start() as u8)
}

/// Stop the engine (clear the run flag, join the thread). Returns 1 if an engine
/// was running, 0 if none. Safe to call on quit.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_stop() -> u8 {
    guard_val(0, || crate::host::engine_stop() as u8)
}

/// Ask the running engine to re-read its config (no restart). Returns 1 if an
/// engine is running, else 0.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_reload() -> u8 {
    guard_val(0, || crate::host::engine_reload() as u8)
}

/// Set global MUTE (the tray "Mute" checkbox). `on != 0` mutes — playback keeps draining,
/// only the audio is silenced. Sent to the running engine over IPC (the same channel the
/// status read uses); returns 1 if the request was delivered, 0 if the engine is down.
#[unsafe(no_mangle)]
pub extern "C" fn ds_set_muted(on: u8) -> u8 {
    guard_val(0, || {
        let Some(paths) = ds_config::Paths::resolve() else {
            return 0;
        };
        match ds_ipc::request(
            &paths.engine_sock,
            &ds_ipc::Request::SetMuted { on: on != 0 },
        ) {
            Ok(ds_ipc::Response::Done) => 1,
            _ => 0,
        }
    })
}

/// Open the OS's system-voice settings page (macOS Spoken Content / Windows Speech / TODO Linux).
/// Cross-platform seam for the UI "Manage voices" button. Returns 1 if launched, 0 otherwise. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_open_voice_settings() -> u8 {
    guard_val(0, || ds_tts::system::open_voice_settings() as u8)
}

/// Run `f`, returning its documented failure default on panic. Panics must not
/// cross the FFI boundary.
fn guard_val<T>(default: T, f: impl FnOnce() -> T) -> T {
    catch_unwind(AssertUnwindSafe(f)).unwrap_or(default)
}

/// Like [`guard_val`] but for the string-returning FFI fns below: `default` is a static
/// fallback string, turned into a heap `CString` only on the (rare) panic path. Using
/// `guard_val(to_cstring(default), ...)` instead would eagerly allocate that fallback
/// `CString` on EVERY call (the overwhelmingly common non-panicking path included), then
/// silently leak it: `Result::unwrap_or` drops the unused `Ok`/`Err` value, and dropping a
/// `*mut c_char` runs no destructor, so the eagerly-allocated bytes are never freed. Only
/// building the fallback in the panic branch (via `unwrap_or_else`) avoids that leak.
fn guard_str(default: &'static str, f: impl FnOnce() -> *mut c_char) -> *mut c_char {
    catch_unwind(AssertUnwindSafe(f)).unwrap_or_else(|_| to_cstring(default))
}

/// Allocate a Rust string into a heap C string the caller frees with
/// `ds_string_free`. An interior NUL (impossible in our data) → "".
fn to_cstring(s: impl Into<Vec<u8>>) -> *mut c_char {
    match CString::new(s) {
        Ok(c) => c.into_raw(),
        Err(_) => CString::new("").unwrap().into_raw(),
    }
}

/// Read an inbound C string into an owned String (empty if NULL or invalid UTF-8).
fn cstr_or_empty(p: *const c_char) -> String {
    cstr_or(p, "")
}

/// Read an inbound C string, substituting `default` for a NULL pointer OR invalid
/// UTF-8 (a VALID string — including an empty one — is returned as-is). The one
/// place the NULL/bad-UTF-8 fallback is decided; each caller passes its own
/// intended default explicitly.
fn cstr_or(p: *const c_char, default: &str) -> String {
    if p.is_null() {
        return default.to_string();
    }
    // SAFETY: `p` is non-null (checked above); per this C ABI's contract the caller
    // passes a NUL-terminated string that stays valid for the call, and the borrowed
    // CStr is copied into an owned String before returning.
    unsafe { std::ffi::CStr::from_ptr(p) }
        .to_str()
        .unwrap_or(default)
        .to_string()
}

/// Kokoro (TTS) model set present + valid? (disk probe only). HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_kokoro_present_global() -> u8 {
    guard_val(0, || models::is_kokoro_present() as u8)
}

/// Is the FULL Parakeet-ONNX (STT) asset set present + valid? HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_parakeet_onnx_present_global() -> u8 {
    guard_val(0, || models::is_parakeet_onnx_present() as u8)
}

/// Engine running? (pidfile probe). HANDLE-FREE, safe off main thread.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_running_global() -> u8 {
    guard_val(0, || engine::is_running() as u8)
}

/// The engine's model-status JSON (presence + per-subsystem running map). Owned
/// `char*` the caller frees with `ds_string_free`; `"{}"` if the engine is
/// down. HANDLE-FREE — safe off the main thread.
#[unsafe(no_mangle)]
pub extern "C" fn ds_model_status_json() -> *mut c_char {
    guard_str("{}", || {
        let Some(paths) = ds_config::Paths::resolve() else {
            return to_cstring("{}");
        };
        match ds_ipc::request(&paths.engine_sock, &ds_ipc::Request::ModelStatus) {
            Ok(ds_ipc::Response::ModelStatus { status }) => to_cstring(status.to_string()),
            _ => to_cstring("{}"),
        }
    })
}

/// Like [`ds_model_status_json`] but BLOCKS until the engine's status sequence
/// differs from `since`, or `timeout_ms` elapses — then returns the current status
/// JSON (whose `seq` field is the new sequence to pass as `since` next time). This is
/// the PUSH transport for the dictation overlay: the UI calls it on a DEDICATED
/// background thread (never the UI thread — it blocks) in a loop, re-rendering the
/// instant a partial lands instead of polling on a timer. Pass `since = 0` first
/// (returns immediately with the current state). Owned `char*`, free with
/// `ds_string_free`; `"{}"` if the engine is down.
#[unsafe(no_mangle)]
pub extern "C" fn ds_model_status_wait(since: u64, timeout_ms: u32) -> *mut c_char {
    guard_str("{}", || {
        let Some(paths) = ds_config::Paths::resolve() else {
            return to_cstring("{}");
        };
        match ds_ipc::request(
            &paths.engine_sock,
            &ds_ipc::Request::WaitModelStatus {
                since,
                timeout_ms: timeout_ms as u64,
            },
        ) {
            Ok(ds_ipc::Response::ModelStatus { status }) => to_cstring(status.to_string()),
            _ => to_cstring("{}"),
        }
    })
}

/// The tool catalog for the app's Tools window — a JSON array of
/// `{name, description, params:[…]}` with the args as an ORDERED array (the UI form of
/// the SAME `ds-tools` catalog the MCP server exposes, so it never drifts from what Claude
/// can call). Each param is enriched with a localized `detail` qualifier (enum allowed-values
/// or a numeric range) via [`crate::status_fmt::tool_param_detail`], so every host renders
/// the SAME pre-built string instead of re-deriving it. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE — no engine.
#[unsafe(no_mangle)]
pub extern "C" fn ds_tools_json() -> *mut c_char {
    guard_str("[]", || {
        let mut catalog = ds_tools::catalog_ui();
        if let Some(tools) = catalog.as_array_mut() {
            for tool in tools {
                let Some(params) = tool.get_mut("params").and_then(|p| p.as_array_mut()) else {
                    continue;
                };
                for param in params {
                    let detail = crate::status_fmt::tool_param_detail(param);
                    if let Some(obj) = param.as_object_mut() {
                        obj.insert("detail".into(), serde_json::Value::String(detail));
                    }
                }
            }
        }
        to_cstring(catalog.to_string())
    })
}

/// The third-party libraries catalog for the app's Libraries window — a JSON array of
/// `{name, usage, homepage, license, license_url, files:[{name, url, size_bytes?}]}`,
/// collected from the SAME download registry every platform fetches from (so the credits
/// can't drift from what's actually shipped). Scope is the downloaded models + runtime.
/// Owned `char*`, free with `ds_string_free`. HANDLE-FREE — no engine.
#[unsafe(no_mangle)]
pub extern "C" fn ds_libraries_json() -> *mut c_char {
    guard_str("[]", || {
        to_cstring(ds_model::libraries::catalog().to_string())
    })
}

/// The COMBINED activity-log tail for the app's Logs tab — a JSON array of
/// `{source, level, text}` merging the unified log (each line tagged engine/tts/stt/caps/hook/
/// mcp/config) with every sibling auxiliary log (e.g. the out-of-process `helper` stderr), in
/// rough chronological order. `max_bytes` caps the tail PER file. Opens SHARED-read (works while
/// the engine appends); the UI derives its source filter from the distinct `source` values.
/// "[]" when there's no log yet. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_logs_json(max_bytes: u32) -> *mut c_char {
    guard_str("[]", || match ds_config::Paths::resolve() {
        Some(paths) => to_cstring(ds_log::combined_log_json(&paths.log_file, max_bytes as u64)),
        None => to_cstring("[]"),
    })
}

/// Like [`ds_logs_json`] but BLOCKS until the logs directory changes (any `*.log` file
/// created/modified/removed — the unified log or a sibling aux log; rotated `*.log.N` files
/// don't count) or `timeout_ms` elapses, then returns the CURRENT combined log JSON — the SAME
/// shape `ds_logs_json` returns, no diff/since token (unlike `ds_model_status_wait`, there's no
/// cross-call sequence to echo back — the caller just re-renders the full tail each time). This
/// is CLIENT-SIDE (an fs watch in the calling process), NOT an engine-IPC round-trip like the
/// status wait — logs are read straight off disk here, same as `ds_logs_json`. Call ONLY on a
/// DEDICATED background thread (it blocks up to `timeout_ms`), in a loop: call → render → call
/// again. `max_bytes` caps the tail PER file, same as `ds_logs_json`. Owned `char*`, free with
/// `ds_string_free`; `"[]"` if `Paths` can't resolve. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_logs_wait(max_bytes: u32, timeout_ms: u32) -> *mut c_char {
    guard_str("[]", || {
        let Some(paths) = ds_config::Paths::resolve() else {
            return to_cstring("[]");
        };
        ds_log::wait_logs_changed(
            &paths.log_file,
            std::time::Duration::from_millis(timeout_ms as u64),
        );
        to_cstring(ds_log::combined_log_json(&paths.log_file, max_bytes as u64))
    })
}

/// Erase the ENTIRE on-disk activity log — the unified log, its rotated backups, and every
/// sibling auxiliary log — for the Logs tab's Clear button. Irreversible; the caller must confirm
/// with the user before calling. A no-op (not an error) if there's nothing on disk yet.
/// HANDLE-FREE — no engine.
#[unsafe(no_mangle)]
pub extern "C" fn ds_logs_clear() {
    guard_val((), || {
        if let Some(paths) = ds_config::Paths::resolve() {
            ds_log::clear_logs(&paths.log_file);
        }
    })
}

/// The product homepage URL (e.g. the About screen's clickable link) — a single
/// source of truth so every platform's UI opens the same address. Owned `char*`,
/// free with `ds_string_free`. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_homepage_url() -> *mut c_char {
    guard_str("", || to_cstring(crate::HOMEPAGE_URL))
}

/// Brand colors (hex sRGB) as a JSON object — the single cross-platform source of truth so
/// macOS + Windows render identical tints (the visual analogue of the shared ds-i18n
/// string catalog). Keys: `seed_purple`, `mic_orange`, `warning`. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_brand_colors_json() -> *mut c_char {
    guard_str("{}", || to_cstring(crate::BRAND_COLORS_JSON))
}

/// Logs-tab colors as a JSON object (`{levels:{ERROR,WARN}, source_palette:[…]}`) — the single
/// cross-platform source of truth for the activity-log view's coloring, so every platform's Logs
/// tab tints identically (sibling of `ds_brand_colors_json`). Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE — no engine.
#[unsafe(no_mangle)]
pub extern "C" fn ds_log_colors_json() -> *mut c_char {
    guard_str("{}", || to_cstring(crate::LOG_COLORS_JSON))
}

/// The product version (the Rust workspace version) for the About screen — one
/// shared source for every platform's UI. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_version() -> *mut c_char {
    guard_str("", || to_cstring(crate::VERSION))
}

/// Startup update check: is a newer DontSpeak release out? Hits the real GitHub API (a
/// blocking HTTP GET — this is the one FFI call that touches the network, NOT handle-free the
/// way the disk/IPC-only probes above are; call it off the UI thread, e.g. once at startup on
/// a background thread) and compares the latest release tag against [`crate::VERSION`] via
/// [`ds_model::update_check::check_for_update_at`]. Returns a JSON object:
/// `{"update_available":bool,"current_version":str,"latest_version":str,"html_url":str}` — the
/// per-host UI reads `update_available` to decide whether to show the pill next to the version
/// number, `latest_version` as the version it displays, and `html_url` as the pill's own
/// click-through target. On ANY failure (offline, rate-limited, malformed response) returns
/// `"{}"` — a host must treat a missing `update_available` key the same as `false`, never as
/// "unknown, so show the pill anyway". Owned `char*`, free with `ds_string_free`.
#[unsafe(no_mangle)]
pub extern "C" fn ds_update_check_json() -> *mut c_char {
    ds_update_check_json_at("https://api.github.com")
}

/// Split out from [`ds_update_check_json`] ONLY so its test can point `api_base` at a mock
/// server instead of the real GitHub API — exercises the real marshaling (`guard_str`/
/// `to_cstring`) and the real [`crate::VERSION`], not a duplicate of `ds-model`'s own unit
/// tests for [`ds_model::update_check::check_for_update_at`] itself.
fn ds_update_check_json_at(api_base: &str) -> *mut c_char {
    guard_str("{}", || {
        let json = ds_model::update_check::check_for_update_at(api_base, crate::VERSION)
            .map(|info| info.to_json())
            .unwrap_or_else(|_| "{}".to_string());
        to_cstring(json)
    })
}

// ── Localization (shared ds-i18n catalog) ────────────────────────────────────────
// Every platform UI renders ONE catalog through these: macOS (Swift) and Windows
// (WinUI) call them instead of hardcoding/duplicating literals. English is the
// fallback; the active locale defaults to the OS language (sys-locale), overridable.

/// Set the active UI locale (BCP-47 or a bare language tag, e.g. "de"). NULL is a no-op.
/// Unknown locales fall back to English at lookup. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_set_locale(locale: *const c_char) {
    guard_val((), || {
        let loc = cstr_or_empty(locale);
        if !loc.is_empty() {
            ds_i18n::set_locale(&loc);
        }
    });
}

/// The active UI locale tag — so a UI can match its native number formatter to the
/// catalog's language. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_locale() -> *mut c_char {
    guard_str("en", || to_cstring(ds_i18n::locale()))
}

/// Look up a localized UI string by `key` (a C string). English fallback; a missing key
/// returns the key itself. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_t(key: *const c_char) -> *mut c_char {
    guard_str("", || to_cstring(ds_i18n::t(&cstr_or_empty(key))))
}

/// Look up a localized string and interpolate `%{name}` placeholders from `args_json`, a
/// JSON object `{ "name": value }` (values stringified). Both args are C strings. Owned
/// `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_t_args(key: *const c_char, args_json: *const c_char) -> *mut c_char {
    guard_str("", || {
        to_cstring(ds_i18n::t_args_json(
            &cstr_or_empty(key),
            &cstr_or_empty(args_json),
        ))
    })
}

// ── Shared status-panel formatters (one implementation, every UI) ────────────────
// The small NON-numeric label assembly the status panels used to duplicate. Both the
// macOS SwiftUI app and the Windows WinUI app call these instead of reimplementing
// them. Culture-sensitive NUMBER formatting (RTF ranges, MB/GB, %) stays in each UI.

/// Localized hover word for an engine lifecycle state. `state` is the model-status token from
/// the canonical [`ds_status::EngineState`] vocabulary ("running"|"idle"|"warming"|
/// "downloading"|"failed"|"blocked"|"missing"),
/// `progress` the 0..1 OVERALL download fraction — byte-weighted across the whole model set, a
/// single global percent (only used for "downloading"), `why` the
/// failure reason (only used for "failed"; empty → the generic default). Owned `char*`,
/// free with `ds_string_free`. HANDLE-FREE. The ONE state→word formatter shared by every UI.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_state_word(
    state: *const c_char,
    progress: f64,
    why: *const c_char,
) -> *mut c_char {
    guard_str("", || {
        to_cstring(crate::status_fmt::engine_state_word(
            &cstr_or_empty(state),
            progress,
            &cstr_or_empty(why),
        ))
    })
}

/// Localized lifetime duration down to seconds, leading zero-units dropped
/// (e.g. "12m 04s", "1d 02h 03m 04s"). Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_duration_live(secs: f64) -> *mut c_char {
    guard_str("", || to_cstring(crate::status_fmt::duration_live(secs)))
}

/// Localized RUNTIME label for a resolved provider token ("ane"|"coreml"|"cuda"|
/// "cpu"; unknown passes through). The TTS/STT runtime detail. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_runtime_label(provider: *const c_char) -> *mut c_char {
    guard_str("", || {
        to_cstring(crate::status_fmt::runtime_label(&cstr_or_empty(provider)))
    })
}

/// A stat RANGE string — "avg`<unit>`  ·  lo–hi". `precision` = decimals; `unit_key` = the
/// catalog key for the trailing unit ("status.stats.unit.times" / ".seconds"). Owned `char*`,
/// free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_stats_range(
    lo: f64,
    avg: f64,
    hi: f64,
    precision: u32,
    unit_key: *const c_char,
) -> *mut c_char {
    guard_str("", || {
        to_cstring(crate::status_fmt::stats_range(
            lo,
            avg,
            hi,
            precision as usize,
            &cstr_or_empty(unit_key),
        ))
    })
}

/// A COUNT + audio-duration stat string — "`<count>`  <audio_secs> s". Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_stats_count(count: u64, audio_secs: f64) -> *mut c_char {
    guard_str("", || {
        to_cstring(crate::status_fmt::stats_count(count, audio_secs))
    })
}

/// A human-readable file size — decimal units, "1.4 GB" / "325 MB" / "12 KB" / "512 B". The ONE
/// size formatter shared by every UI's Libraries/Credits tab. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_human_size(bytes: u64) -> *mut c_char {
    guard_str("", || to_cstring(crate::status_fmt::human_size(bytes)))
}

/// Set the TTS execution provider for this session: `provider` is "cpu" | "cuda" |
/// "coreml" | "ane" | "auto" (NULL/unknown → "auto"). The engine restarts the warm Kokoro child on
/// the new provider and resets its TTS stats (only if the active provider actually
/// changed). Returns 1 if the request reached the engine, else 0. The new provider
/// + fresh stats then show up via `ds_model_status_json`.
#[unsafe(no_mangle)]
pub extern "C" fn ds_set_provider(provider: *const c_char) -> u8 {
    guard_val(0, || {
        // NULL/invalid-UTF-8 → "auto" (let the engine pick the provider).
        let provider = cstr_or(provider, "auto");
        let Some(paths) = ds_config::Paths::resolve() else {
            return 0;
        };
        match ds_ipc::request(
            &paths.engine_sock,
            &ds_ipc::Request::SetProvider { provider },
        ) {
            Ok(ds_ipc::Response::Done) => 1,
            _ => 0,
        }
    })
}

/// Free a `char*` returned by any ds_* function. NULL is a no-op.
#[unsafe(no_mangle)]
pub extern "C" fn ds_string_free(s: *mut c_char) {
    guard_val((), || {
        if !s.is_null() {
            // SAFETY: per `ds_string_free`'s contract, `s` is a pointer previously
            // returned by `to_cstring` (CString::into_raw) and not yet freed — from_raw
            // reclaims that exact allocation exactly once; NULL was screened out above.
            unsafe { drop(CString::from_raw(s)) };
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The new FFI-boundary function itself, not a duplicate of `ds-model`'s own httpmock unit
    /// tests for `check_for_update_at`: goes through the real `ds_update_check_json_at` seam
    /// (same `guard_str`/`to_cstring` marshaling `ds_update_check_json` uses), pointed at a
    /// mock server so it never touches the real GitHub API on `cargo test`.
    #[test]
    fn ds_update_check_json_at_reads_a_mocked_release_through_the_real_ffi_path() {
        let server = httpmock::MockServer::start();
        let mock = server.mock(|when, then| {
            when.method(httpmock::Method::GET)
                .path("/repos/delllusional/DontSpeak/releases/latest");
            then.status(200).json_body(serde_json::json!({
                "tag_name": "v9.9.9",
                "html_url": "https://github.com/delllusional/DontSpeak/releases/tag/v9.9.9",
            }));
        });

        let ptr = ds_update_check_json_at(&server.base_url());
        // SAFETY: `ptr` was just returned by ds_update_check_json_at, which always
        // yields a non-null, NUL-terminated C string (guard_str/to_cstring); it is
        // freed only after this read, via ds_string_free below.
        let json = unsafe { std::ffi::CStr::from_ptr(ptr) }
            .to_str()
            .unwrap()
            .to_owned();
        ds_string_free(ptr);
        mock.assert();

        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["update_available"], true);
        assert_eq!(v["latest_version"], "9.9.9");
    }

    /// A failing endpoint must degrade to `"{}"`, never propagate an error to the caller.
    #[test]
    fn ds_update_check_json_at_degrades_to_empty_object_on_a_failing_endpoint() {
        let server = httpmock::MockServer::start();
        let mock = server.mock(|when, then| {
            when.method(httpmock::Method::GET)
                .path("/repos/delllusional/DontSpeak/releases/latest");
            then.status(404);
        });

        let ptr = ds_update_check_json_at(&server.base_url());
        // SAFETY: `ptr` was just returned by ds_update_check_json_at, which always
        // yields a non-null, NUL-terminated C string (guard_str/to_cstring); it is
        // freed only after this read, via ds_string_free below.
        let json = unsafe { std::ffi::CStr::from_ptr(ptr) }
            .to_str()
            .unwrap()
            .to_owned();
        ds_string_free(ptr);
        mock.assert();

        assert_eq!(json, "{}");
    }

    /// End-to-end: the UI tool catalog the hosts read (`ds_tools_json`) enriches EVERY param
    /// with a `detail` string, and constraint params carry the shared localized qualifier — so
    /// no host has to rebuild it. Guards the FFI enrichment, not just the formatter helper.
    #[test]
    fn ds_tools_json_enriches_every_param_with_detail() {
        let ptr = ds_tools_json();
        // SAFETY: `ptr` was just returned by ds_tools_json, which always yields a
        // non-null, NUL-terminated C string (guard_str/to_cstring); it is freed only
        // after this read, via ds_string_free below.
        let json = unsafe { std::ffi::CStr::from_ptr(ptr) }
            .to_str()
            .unwrap()
            .to_owned();
        ds_string_free(ptr);

        let catalog: serde_json::Value = serde_json::from_str(&json).unwrap();
        let tools = catalog.as_array().expect("catalog is an array");
        let mut saw_enum = false;
        for tool in tools {
            for param in tool["params"].as_array().unwrap_or(&Vec::new()) {
                // Every param gets the key (even when empty) so hosts read it unconditionally.
                let detail = param
                    .get("detail")
                    .and_then(|d| d.as_str())
                    .expect("param has a detail field");
                // A param with an `enum` MUST surface the localized "one of: …" qualifier.
                if param
                    .get("enum")
                    .and_then(|e| e.as_array())
                    .is_some_and(|v| !v.is_empty())
                {
                    saw_enum = true;
                    assert!(
                        detail.starts_with("one of: "),
                        "enum param {} → {detail:?}",
                        param["name"]
                    );
                }
            }
        }
        assert!(saw_enum, "catalog has at least one enum param to qualify");
    }
}
