// ffi.rs is the C-ABI boundary: these `extern "C"` entry points deref pointers
// supplied by the C/Swift caller, which owns their validity — not us.
#![allow(clippy::not_unsafe_ptr_arg_deref)]

//! The stable C ABI the native UI links (committed `dontspeak.h`, generated by
//! cbindgen). The app is an informational menu-bar + health panel, so this
//! surface is small and HANDLE-FREE (no opaque handle type): read-only probes,
//! the in-process engine lifecycle (start/stop/reload), a few session controls
//! (mute, TTS provider, locale), shared UI constants/formatters/i18n lookups,
//! and the string free. The rich control surface
//! (voice/engine/language/rate/toggles/downloads) lives in DontSpeak.

use std::ffi::{CString, c_char};
use std::panic::{AssertUnwindSafe, catch_unwind};

use crate::{engine, models};

// ── In-process engine host ───────────────────────────────────────────────────
// The lifecycle state lives in [`crate::host`] (the ONE owner, kept out of this boundary so
// a stray second start can't spawn a competing engine); these C entry points are thin
// adapters returning the u8 the committed `dontspeak.h` documents.

/// Start the engine on a background thread if not already running. Returns 1 if
/// it is now running (started or already up), 0 on failure.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_start() -> u8 {
    guard_val(0, || crate::host::engine_start() as u8)
}

/// Stop the engine (clear the run flag, join the thread). Returns 1 if an engine
/// was running, 0 if none. Safe to call on quit.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_stop() -> u8 {
    guard_val(0, || crate::host::engine_stop() as u8)
}

/// Ask the running engine to re-read its config (no restart). Returns 1 if an
/// engine is running, else 0.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_reload() -> u8 {
    guard_val(0, || crate::host::engine_reload() as u8)
}

/// Set global MUTE (the tray "Mute" checkbox). `on != 0` mutes — playback keeps draining,
/// only the audio is silenced. Sent to the running engine over IPC (the same channel the
/// status read uses); returns 1 if the request was delivered, 0 if the engine is down.
#[unsafe(no_mangle)]
pub extern "C" fn ds_set_muted(on: u8) -> u8 {
    guard_val(0, || {
        let Some(paths) = ds_config::Paths::resolve() else {
            return 0;
        };
        match ds_ipc::request(
            &paths.engine_sock,
            &ds_ipc::Request::SetMuted { on: on != 0 },
        ) {
            Ok(_) => 1,
            Err(_) => 0,
        }
    })
}

/// Open the OS's system-voice settings page — Spoken Content (macOS) / Time & language ▸
/// Speech (Windows) / TODO (Linux). The cross-platform seam behind every UI's System-TTS
/// "Manage voices" affordance, so each platform launches the same per-OS page from one call.
/// Returns 1 if a page was launched, 0 if unsupported/failed. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_open_voice_settings() -> u8 {
    guard_val(0, || ds_tts::system::open_voice_settings() as u8)
}

/// Run `f`, returning `default` on a panic (panics must never cross the FFI
/// boundary). All exported fns are read-only, so a default is always safe.
fn guard_val<T>(default: T, f: impl FnOnce() -> T) -> T {
    catch_unwind(AssertUnwindSafe(f)).unwrap_or(default)
}

/// Allocate a Rust string into a heap C string the caller frees with
/// `ds_string_free`. An interior NUL (impossible in our data) → "".
fn to_cstring(s: impl Into<Vec<u8>>) -> *mut c_char {
    match CString::new(s) {
        Ok(c) => c.into_raw(),
        Err(_) => CString::new("").unwrap().into_raw(),
    }
}

/// Read an inbound C string into an owned String (empty if NULL or invalid UTF-8).
fn cstr_or_empty(p: *const c_char) -> String {
    cstr_or(p, "")
}

/// Read an inbound C string, substituting `default` for a NULL pointer OR invalid
/// UTF-8 (a VALID string — including an empty one — is returned as-is). The one
/// place the NULL/bad-UTF-8 fallback is decided; each caller passes its own
/// intended default explicitly.
fn cstr_or(p: *const c_char, default: &str) -> String {
    if p.is_null() {
        return default.to_string();
    }
    unsafe { std::ffi::CStr::from_ptr(p) }
        .to_str()
        .unwrap_or(default)
        .to_string()
}

/// Is the Kokoro (TTS) model set present + valid? HANDLE-FREE (probes disk only),
/// so the UI can poll it off the main thread.
#[unsafe(no_mangle)]
pub extern "C" fn ds_kokoro_present_global() -> u8 {
    guard_val(0, || models::kokoro_present() as u8)
}

/// Is the FULL Parakeet-ONNX (STT) asset set present + valid? HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_parakeet_onnx_present_global() -> u8 {
    guard_val(0, || models::parakeet_onnx_present() as u8)
}

/// Is the engine running? HANDLE-FREE (pidfile + launchctl probe), safe off the
/// main thread.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_running_global() -> u8 {
    guard_val(0, || engine::is_running() as u8)
}

/// The engine's model-status JSON (presence + per-subsystem running map). Owned
/// `char*` the caller frees with `ds_string_free`; `"{}"` if the engine is
/// down. HANDLE-FREE — safe off the main thread.
#[unsafe(no_mangle)]
pub extern "C" fn ds_model_status_json() -> *mut c_char {
    guard_val(to_cstring("{}"), || {
        let Some(paths) = ds_config::Paths::resolve() else {
            return to_cstring("{}");
        };
        match ds_ipc::request(&paths.engine_sock, &ds_ipc::Request::ModelStatus) {
            Ok(ds_ipc::Response::ModelStatus { status }) => to_cstring(status.to_string()),
            _ => to_cstring("{}"),
        }
    })
}

/// Like [`ds_model_status_json`] but BLOCKS until the engine's status sequence
/// differs from `since`, or `timeout_ms` elapses — then returns the current status
/// JSON (whose `seq` field is the new sequence to pass as `since` next time). This is
/// the PUSH transport for the dictation overlay: the UI calls it on a DEDICATED
/// background thread (never the UI thread — it blocks) in a loop, re-rendering the
/// instant a partial lands instead of polling on a timer. Pass `since = 0` first
/// (returns immediately with the current state). Owned `char*`, free with
/// `ds_string_free`; `"{}"` if the engine is down.
#[unsafe(no_mangle)]
pub extern "C" fn ds_model_status_wait(since: u64, timeout_ms: u32) -> *mut c_char {
    guard_val(to_cstring("{}"), || {
        let Some(paths) = ds_config::Paths::resolve() else {
            return to_cstring("{}");
        };
        match ds_ipc::request(
            &paths.engine_sock,
            &ds_ipc::Request::WaitModelStatus {
                since,
                timeout_ms: timeout_ms as u64,
            },
        ) {
            Ok(ds_ipc::Response::ModelStatus { status }) => to_cstring(status.to_string()),
            _ => to_cstring("{}"),
        }
    })
}

/// The tool catalog for the app's Tools window — a JSON array of
/// `{name, description, params:[…]}` with the args as an ORDERED array (the UI form of
/// the SAME `ds-tools` catalog the MCP server exposes, so it never drifts from what Claude
/// can call). Owned `char*`, free with `ds_string_free`. HANDLE-FREE — no engine.
#[unsafe(no_mangle)]
pub extern "C" fn ds_tools_json() -> *mut c_char {
    guard_val(to_cstring("[]"), || {
        to_cstring(ds_tools::catalog_ui().to_string())
    })
}

/// The third-party libraries catalog for the app's Libraries window — a JSON array of
/// `{name, usage, homepage, license, license_url, files:[{name, url, size_bytes?}]}`,
/// collected from the SAME download registry every platform fetches from (so the credits
/// can't drift from what's actually shipped). Scope is the downloaded models + runtime.
/// Owned `char*`, free with `ds_string_free`. HANDLE-FREE — no engine.
#[unsafe(no_mangle)]
pub extern "C" fn ds_libraries_json() -> *mut c_char {
    guard_val(to_cstring("[]"), || {
        to_cstring(ds_model::libraries::catalog().to_string())
    })
}

/// The COMBINED activity-log tail for the app's Logs tab — a JSON array of
/// `{source, level, text}` merging the unified log (each line tagged engine/tts/stt/caps/hook/
/// mcp/config) with every sibling auxiliary log (e.g. the out-of-process `helper` stderr), in
/// rough chronological order. `max_bytes` caps the tail PER file. Opens SHARED-read (works while
/// the engine appends); the UI derives its source filter from the distinct `source` values.
/// "[]" when there's no log yet. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_logs_json(max_bytes: u32) -> *mut c_char {
    guard_val(to_cstring("[]"), || match ds_config::Paths::resolve() {
        Some(paths) => to_cstring(ds_config::combined_log_json(&paths, max_bytes as u64)),
        None => to_cstring("[]"),
    })
}

/// The product homepage URL (e.g. the About screen's clickable link) — a single
/// source of truth so every platform's UI opens the same address. Owned `char*`,
/// free with `ds_string_free`. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_homepage_url() -> *mut c_char {
    guard_val(to_cstring(""), || to_cstring(crate::HOMEPAGE_URL))
}

/// Brand colors (hex sRGB) as a JSON object — the single cross-platform source of truth so
/// macOS + Windows render identical tints (the visual analogue of the shared ds-i18n
/// string catalog). Keys: `seed_purple`, `mic_orange`, `warning`. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_brand_colors_json() -> *mut c_char {
    guard_val(to_cstring("{}"), || to_cstring(crate::BRAND_COLORS_JSON))
}

/// Logs-tab colors as a JSON object (`{levels:{ERROR,WARN}, source_palette:[…]}`) — the single
/// cross-platform source of truth for the activity-log view's coloring, so every platform's Logs
/// tab tints identically (sibling of `ds_brand_colors_json`). Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE — no engine.
#[unsafe(no_mangle)]
pub extern "C" fn ds_log_colors_json() -> *mut c_char {
    guard_val(to_cstring("{}"), || to_cstring(crate::LOG_COLORS_JSON))
}

/// The product version (the Rust workspace version) for the About screen — one
/// shared source for every platform's UI. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_version() -> *mut c_char {
    guard_val(to_cstring(""), || to_cstring(crate::VERSION))
}

// ── Localization (shared ds-i18n catalog) ────────────────────────────────────────
// Every platform UI renders ONE catalog through these: macOS (Swift) and Windows
// (WinUI) call them instead of hardcoding/duplicating literals. English is the
// fallback; the active locale defaults to the OS language (sys-locale), overridable.

/// Set the active UI locale (BCP-47 or a bare language tag, e.g. "de"). NULL is a no-op.
/// Unknown locales fall back to English at lookup. HANDLE-FREE — no engine needed.
#[unsafe(no_mangle)]
pub extern "C" fn ds_set_locale(locale: *const c_char) {
    guard_val((), || {
        let loc = cstr_or_empty(locale);
        if !loc.is_empty() {
            ds_i18n::set_locale(&loc);
        }
    });
}

/// The active UI locale tag — so a UI can match its native number formatter to the
/// catalog's language. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_locale() -> *mut c_char {
    guard_val(to_cstring("en"), || to_cstring(ds_i18n::locale()))
}

/// Look up a localized UI string by `key` (a C string). English fallback; a missing key
/// returns the key itself. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_t(key: *const c_char) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(ds_i18n::t(&cstr_or_empty(key)))
    })
}

/// Look up a localized string and interpolate `%{name}` placeholders from `args_json`, a
/// JSON object `{ "name": value }` (values stringified). Both args are C strings. Owned
/// `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_t_args(key: *const c_char, args_json: *const c_char) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(ds_i18n::t_args_json(
            &cstr_or_empty(key),
            &cstr_or_empty(args_json),
        ))
    })
}

// ── Shared status-panel formatters (one implementation, every UI) ────────────────
// The small NON-numeric label assembly the status panels used to duplicate. Both the
// macOS SwiftUI app and the Windows WinUI app call these instead of reimplementing
// them. Culture-sensitive NUMBER formatting (RTF ranges, MB/GB, %) stays in each UI.

/// Localized hover word for an engine lifecycle state. `state` is the model-status token from
/// the canonical [`ds_status::EngineState`] vocabulary ("running"|"idle"|"warming"|
/// "downloading"|"failed"|"blocked"|"missing"),
/// `progress` the 0..1 download fraction (only used for "downloading"), `why` the
/// failure reason (only used for "failed"; empty → the generic default). Owned `char*`,
/// free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_state_word(
    state: *const c_char,
    progress: f64,
    why: *const c_char,
) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(crate::status_fmt::engine_state_word(
            &cstr_or_empty(state),
            progress,
            &cstr_or_empty(why),
        ))
    })
}

/// As [`ds_engine_state_word`], plus the in-flight download's `file_index`/`file_count`
/// so a multi-file model set reads "<index>/<count> · Downloading <pct>%". `0`/`0` → plain.
/// Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_engine_state_word_files(
    state: *const c_char,
    progress: f64,
    why: *const c_char,
    file_index: i64,
    file_count: i64,
) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(crate::status_fmt::engine_state_word_files(
            &cstr_or_empty(state),
            progress,
            &cstr_or_empty(why),
            file_index,
            file_count,
        ))
    })
}

/// Localized lifetime duration down to seconds, leading zero-units dropped
/// (e.g. "12m 04s", "1d 02h 03m 04s"). Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_duration_live(secs: f64) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(crate::status_fmt::duration_live(secs))
    })
}

/// Localized RUNTIME label for a resolved provider token ("ane"|"ort_coreml"|"ort_cuda"|
/// "ort_cpu"; unknown passes through). The TTS/STT runtime detail. Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_runtime_label(provider: *const c_char) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(crate::status_fmt::runtime_label(&cstr_or_empty(provider)))
    })
}

/// A stat RANGE string — "avg<unit>  ·  lo–hi". `precision` = decimals; `unit_key` = the
/// catalog key for the trailing unit ("status.stats.unit.times" / ".seconds"). Owned `char*`,
/// free with `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_stats_range(
    lo: f64,
    avg: f64,
    hi: f64,
    precision: u32,
    unit_key: *const c_char,
) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(crate::status_fmt::stats_range(
            lo,
            avg,
            hi,
            precision as usize,
            &cstr_or_empty(unit_key),
        ))
    })
}

/// A COUNT + audio-duration stat string — "<count>  <audio_secs> s". Owned `char*`, free with
/// `ds_string_free`. HANDLE-FREE.
#[unsafe(no_mangle)]
pub extern "C" fn ds_stats_count(count: u64, audio_secs: f64) -> *mut c_char {
    guard_val(to_cstring(""), || {
        to_cstring(crate::status_fmt::stats_count(count, audio_secs))
    })
}

/// Set the TTS execution provider for this session: `which` is "ort_cpu" | "ort_cuda" |
/// "ort_coreml" | "ane" | "auto" (NULL/unknown → "auto"). The engine restarts the warm Kokoro child on
/// the new provider and resets its TTS stats (only if the active provider actually
/// changed). Returns 1 if the request reached the engine, else 0. The new provider
/// + fresh stats then show up via `ds_model_status_json`.
#[unsafe(no_mangle)]
pub extern "C" fn ds_set_provider(which: *const c_char) -> u8 {
    guard_val(0, || {
        // NULL/invalid-UTF-8 → "auto" (let the engine pick the provider).
        let which = cstr_or(which, "auto");
        let Some(paths) = ds_config::Paths::resolve() else {
            return 0;
        };
        match ds_ipc::request(&paths.engine_sock, &ds_ipc::Request::SetProvider { which }) {
            Ok(ds_ipc::Response::Done) => 1,
            _ => 0,
        }
    })
}

/// Free a `char*` returned by any ds_* function. NULL is a no-op.
#[unsafe(no_mangle)]
pub extern "C" fn ds_string_free(s: *mut c_char) {
    guard_val((), || {
        if !s.is_null() {
            unsafe { drop(CString::from_raw(s)) };
        }
    });
}
