/*
 * dontspeak.h — the stable C ABI for ds-core.
 *
 * Bind this header from ANY native UI: SwiftUI (macOS) today; C#/WinRT
 * (Windows) or GTK/C (Linux) later — all call the SAME functions.
 *
 * The app is an informational menu-bar + health panel, so this surface is
 * intentionally TINY and HANDLE-FREE: a few read-only probes, the in-process
 * engine lifecycle (start/stop/reload), localization, two engine actions
 * (model download, TTS provider), and the string free. ALL config (voice /
 * engine / language / rate / toggles) lives in DontSpeak, NOT here.
 *
 * MEMORY / OWNERSHIP / CONTRACT (read before binding):
 *  - HANDLE-FREE: there is no opaque handle and no create/destroy pair — every
 *    function is free-standing and may be called from any thread (each notes
 *    whether it touches disk / IPC).
 *  - STRINGS: every returned `char*` is heap UTF-8, NUL-terminated, owned by
 *    Rust; free it with ds_string_free() (NEVER libc free()). A returning
 *    function never returns NULL — on any failure it returns an owned empty/`"{}"`
 *    /`"[]"` string you still free. Inbound `const char*` is borrowed for the call
 *    only and copied immediately; NULL is treated as empty / the documented default.
 *  - RETURN CODES: the u8-returning actions return 1 on success and 0 on failure
 *    (engine down, bad input, or a caught panic) — there are no negative error
 *    codes and no out-of-band error channel. Probes return the value directly.
 *  - PANICS: every function catches Rust panics at the boundary and converts them
 *    to the documented default (0, or an owned empty/`"{}"`/`"[]"` string), so a
 *    panic never crosses into C.
 *  - PLATFORM: this ABI is platform-agnostic. Platform specifics (engine reload
 *    via SIGHUP, with a legacy launchctl fallback on macOS) are delegated inside
 *    Rust; a Windows/Linux UI calls the same functions (ds_engine_reload is
 *    a no-op where unsupported).
 *
 * GENERATED by cbindgen from src/ffi.rs — do NOT hand-edit. Run
 * `cargo build -p ds-core --features cbindgen` to regenerate.
 */


#ifndef DONTSPEAK_H
#define DONTSPEAK_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Start the engine on a background thread if not already running. Returns 1 if
// it is now running (started or already up), 0 on failure.
uint8_t ds_engine_start(void);

// Stop the engine (clear the run flag, join the thread). Returns 1 if an engine
// was running, 0 if none. Safe to call on quit.
uint8_t ds_engine_stop(void);

// Ask the running engine to re-read its config (no restart). Returns 1 if an
// engine is running, else 0.
uint8_t ds_engine_reload(void);

// Set global MUTE (the tray "Mute" checkbox). `on != 0` mutes — playback keeps draining,
// only the audio is silenced. Sent to the running engine over IPC (the same channel the
// status read uses); returns 1 if the request was delivered, 0 if the engine is down.
uint8_t ds_set_muted(uint8_t on);

// Open the OS's system-voice settings page — Spoken Content (macOS) / Time & language ▸
// Speech (Windows) / TODO (Linux). The cross-platform seam behind every UI's System-TTS
// "Manage voices" affordance, so each platform launches the same per-OS page from one call.
// Returns 1 if a page was launched, 0 if unsupported/failed. HANDLE-FREE — no engine needed.
uint8_t ds_open_voice_settings(void);

// Is the Kokoro (TTS) model set present + valid? HANDLE-FREE (probes disk only),
// so the UI can poll it off the main thread.
uint8_t ds_kokoro_present_global(void);

// Is the FULL Parakeet-ONNX (STT) asset set present + valid? HANDLE-FREE.
uint8_t ds_parakeet_onnx_present_global(void);

// Is the engine running? HANDLE-FREE (pidfile + launchctl probe), safe off the
// main thread.
uint8_t ds_engine_running_global(void);

// The engine's model-status JSON (presence + per-subsystem running map). Owned
// `char*` the caller frees with `ds_string_free`; `"{}"` if the engine is
// down. HANDLE-FREE — safe off the main thread.
char *ds_model_status_json(void);

// Like [`ds_model_status_json`] but BLOCKS until the engine's status sequence
// differs from `since`, or `timeout_ms` elapses — then returns the current status
// JSON (whose `seq` field is the new sequence to pass as `since` next time). This is
// the PUSH transport for the dictation overlay: the UI calls it on a DEDICATED
// background thread (never the UI thread — it blocks) in a loop, re-rendering the
// instant a partial lands instead of polling on a timer. Pass `since = 0` first
// (returns immediately with the current state). Owned `char*`, free with
// `ds_string_free`; `"{}"` if the engine is down.
char *ds_model_status_wait(uint64_t since, uint32_t timeout_ms);

// The tool catalog for the app's Tools window — a JSON array of
// `{name, description, params:[…]}` with the args as an ORDERED array (the UI form of
// the SAME `ds-tools` catalog the MCP server exposes, so it never drifts from what Claude
// can call). Owned `char*`, free with `ds_string_free`. HANDLE-FREE — no engine.
char *ds_tools_json(void);

// The third-party libraries catalog for the app's Libraries tab — a JSON array of
// `{name, usage, homepage, license, license_url, files:[{name, url, size_bytes?}]}`,
// already FILTERED to this platform (the shared `ds-model` catalog declares each library's
// `platforms`, so a build shows only what it actually downloads — e.g. the Apple-Silicon
// Core ML sets here, never the CUDA/cuDNN GPU runtime). Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine.
char *ds_libraries_json(void);

// The COMBINED activity-log tail for the app's Logs tab — a JSON array of
// `{source, level, text}` merging the unified log with every sibling auxiliary log, in rough
// chronological order; `max_bytes` caps the tail PER file. `"[]"` when there's no log yet.
// Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_logs_json(uint32_t max_bytes);

// Logs-tab colors as a JSON object (`{levels:{ERROR,WARN}, source_palette:[…]}`) — the single
// cross-platform source of truth for the activity-log view's coloring, so every platform's Logs
// tab tints identically (sibling of `ds_brand_colors_json`). Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine.
char *ds_log_colors_json(void);

// The product homepage URL (e.g. the About screen's clickable link) — a single
// source of truth so every platform's UI opens the same address. Owned `char*`,
// free with `ds_string_free`. HANDLE-FREE — no engine needed.
char *ds_homepage_url(void);

// Brand colors (hex sRGB) as a JSON object — the single cross-platform source of truth so
// macOS + Windows render identical tints (the visual analogue of the shared ds-i18n
// string catalog). Keys: `seed_purple`, `mic_orange`, `warning`. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine needed.
char *ds_brand_colors_json(void);

// The product version (the Rust workspace version) for the About screen — one
// shared source for every platform's UI. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine needed.
char *ds_version(void);

// Set the active UI locale (BCP-47 or a bare language tag, e.g. "de"). NULL is a no-op.
// Unknown locales fall back to English at lookup. HANDLE-FREE — no engine needed.
void ds_set_locale(const char *locale);

// The active UI locale tag — so a UI can match its native number formatter to the
// catalog's language. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_locale(void);

// Look up a localized UI string by `key` (a C string). English fallback; a missing key
// returns the key itself. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_t(const char *key);

// Look up a localized string and interpolate `%{name}` placeholders from `args_json`, a
// JSON object `{ "name": value }` (values stringified). Both args are C strings. Owned
// `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_t_args(const char *key, const char *args_json);

// Localized hover word for an engine lifecycle state. `state` is the raw model-status
// string ("running"|"idle"|"warming"|"downloading"|"failed"|"blocked"|"missing"),
// `progress` the 0..1 download fraction (only used for "downloading"), `why` the
// failure reason (only used for "failed"; empty → the generic default). Owned `char*`,
// free with `ds_string_free`. HANDLE-FREE.
char *ds_engine_state_word(const char *state, double progress, const char *why);

// As [`ds_engine_state_word`], plus the in-flight download's `file_index`/`file_count`
// so a multi-file model set reads "<index>/<count> · Downloading <pct>%". `0`/`0` → plain.
// Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_engine_state_word_files(const char *state,
                                       double progress,
                                       const char *why,
                                       int64_t file_index,
                                       int64_t file_count);

// Localized lifetime duration down to seconds, leading zero-units dropped
// (e.g. "12m 04s", "1d 02h 03m 04s"). Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE.
char *ds_duration_live(double secs);

// Localized RUNTIME label for a resolved provider token ("ane"|"ort_coreml"|"ort_cuda"|
// "ort_cpu"; unknown passes through). The TTS/STT runtime detail. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE.
char *ds_runtime_label(const char *provider);

// A stat RANGE string "avg<unit>  ·  lo–hi". `precision` = decimals; `unit_key` = the catalog
// key for the trailing unit. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_stats_range(double lo, double avg, double hi, uint32_t precision, const char *unit_key);

// A COUNT + audio-duration stat string "<count>  <audio_secs> s". Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE.
char *ds_stats_count(uint64_t count, double audio_secs);

// Set the TTS execution provider for this session: `which` is "ort_cpu" | "ort_cuda" |
// "ort_coreml" | "ane" | "auto" (NULL/unknown → "auto"). The engine restarts the warm Kokoro child on
// the new provider and resets its TTS stats (only if the active provider actually
// changed). Returns 1 if the request reached the engine, else 0. The new provider
// + fresh stats then show up via `ds_model_status_json`.
uint8_t ds_set_provider(const char *which);

// Free a `char*` returned by any ds_* function. NULL is a no-op.
void ds_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DONTSPEAK_H */
