/*
 * dontspeak.h — the stable C ABI for ds-core.
 *
 * SwiftUI, WinUI, and GTK hosts all call this same API.
 *
 * The app is an informational menu-bar + health panel, so this surface is
 * intentionally TINY and HANDLE-FREE: a few read-only probes, the in-process
 * engine lifecycle (start/stop/reload), localization, two engine actions
 * (model download, TTS provider), and the string free. ALL config (voice /
 * engine / language / rate / toggles) lives in DontSpeak, NOT here.
 *
 * MEMORY / OWNERSHIP / CONTRACT (read before binding):
 *  - HANDLE-FREE: there is no opaque handle and no create/destroy pair — every
 *    function is free-standing and may be called from any thread (each notes
 *    whether it touches disk / IPC).
 *  - STRINGS: every returned `char*` is heap UTF-8, NUL-terminated, owned by
 *    Rust; free it with ds_string_free() (NEVER libc free()). A returning
 *    function never returns NULL — on any failure it returns an owned empty/`"{}"`
 *    /`"[]"` string you still free. Inbound `const char*` is borrowed for the call
 *    only and copied immediately; NULL is treated as empty / the documented default.
 *  - RETURN CODES: the u8-returning actions return 1 on success and 0 on failure
 *    (engine down, bad input, or a caught panic) — there are no negative error
 *    codes and no out-of-band error channel. Probes return the value directly.
 *  - PANICS: every function catches Rust panics at the boundary and converts them
 *    to the documented default (0, or an owned empty/`"{}"`/`"[]"` string), so a
 *    panic never crosses into C.
 *  - PLATFORM: this ABI is platform-agnostic. Platform specifics (input capture,
 *    key injection, permission prompts) are delegated inside Rust; every host —
 *    macOS, Windows, Linux — calls the same functions in-process.
 *
 * GENERATED by cbindgen from src/ffi.rs — do NOT hand-edit. Run
 * `cargo build -p ds-core --features cbindgen` to regenerate.
 */


#ifndef DONTSPEAK_H
#define DONTSPEAK_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Saturation of the pastel base (0…1).
#define PASTEL_S 0.42

// Value/brightness of the pastel base (0…1).
#define PASTEL_V 0.92

// Overlay alpha applied by hosts on the speaking Usage card.
#define WASH_ALPHA 0.30

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// 1 = ok.
uint8_t ds_engine_start(void);

// 1 if was running. Safe on quit.
uint8_t ds_engine_stop(void);

// 1 if ok.
uint8_t ds_engine_reload(void);

// Mute (`on != 0`); playback drains. 1 if IPC delivered.
uint8_t ds_set_muted(uint8_t on);

// OS voice settings. 0 on Linux (#74). HANDLE-FREE.
uint8_t ds_open_voice_settings(void);

// Kokoro present+valid? Disk probe. HANDLE-FREE.
uint8_t ds_kokoro_present_global(void);

// Full Parakeet-ONNX set present+valid? HANDLE-FREE.
uint8_t ds_parakeet_onnx_present_global(void);

// Pidfile probe. HANDLE-FREE, off-main-thread ok.
uint8_t ds_engine_running_global(void);

// Model-status JSON. Owned `char*` (`ds_string_free`); `"{}"` if down. HANDLE-FREE.
char *ds_model_status_json(void);

// Block until `seq` ≠ `since` or timeout. Overlay push: background thread loop
// (`since = 0` first). Owned `char*`; `"{}"` if down.
char *ds_model_status_wait(uint64_t since, uint32_t timeout_ms);

// Usage skeleton (`ds_agent_usage::skeleton`). No network. Owned `char*`. HANDLE-FREE.
char *ds_agent_usage_skeleton_json(void);

// Blocking card refresh (`ClientSource` token). Off UI thread. `refresh` skips soft cache.
// Owned `char*`. HANDLE-FREE.
char *ds_agent_usage_card_json(const char *agent, uint8_t refresh);

// USER-INITIATED authorize + forced card refresh. BLOCKING: network plus, on
// macOS, possibly the keychain ACL credential dialog. Host contract: off the UI
// thread, explicit click only — never startup / tab paint / MCP. Owned `char*`.
// HANDLE-FREE.
char *ds_agent_usage_card_authorize_json(const char *agent);

// Aggregate refresh (tests/tooling). Owned `char*`. HANDLE-FREE.
char *ds_agent_usage_json(uint8_t refresh);

// Tools-window catalog: JSON array `{name, description, params:[…]}` — ordered params,
// same `ds-tools` catalog as MCP (no drift). Each param gets localized `detail` via
// [`crate::status_fmt::tool_param_detail`]. Owned `char*`. HANDLE-FREE.
char *ds_tools_json(void);

// Libraries/credits catalog from the same download registry every platform fetches
// (models + runtime). Owned `char*`. HANDLE-FREE.
char *ds_libraries_json(void);

// Combined activity-log tail for Logs tab: `{source, level, text}` merging unified log
// with sibling aux logs. `max_bytes` per file; shared-read while engine appends.
// `"[]"` if none. Owned `char*`. HANDLE-FREE.
char *ds_logs_json(uint32_t max_bytes);

// Like [`ds_logs_json`] but BLOCKS until any `*.log` in the logs dir changes (not
// rotated `*.log.N`) or `timeout_ms` elapses, then returns the full current tail (no
// since-token). Client-side fs watch, not engine IPC. Dedicated background thread only.
// Owned `char*`; `"[]"` if Paths fail. HANDLE-FREE.
char *ds_logs_wait(uint32_t max_bytes, uint32_t timeout_ms);

// Erase entire on-disk activity log (unified + rotated + aux). Irreversible — UI must
// confirm. No-op if empty. HANDLE-FREE.
void ds_logs_clear(void);

// Product homepage URL — single source for every platform. Owned `char*`. HANDLE-FREE.
char *ds_homepage_url(void);

// Brand colors JSON (`seed_purple`, `mic_orange`, `warning`) — single cross-platform
// source. Owned `char*`. HANDLE-FREE.
char *ds_brand_colors_json(void);

// Logs-tab colors JSON (`levels`, `source_palette`) — sibling of `ds_brand_colors_json`.
// Owned `char*`. HANDLE-FREE.
char *ds_log_colors_json(void);

// One random Usage speaking-card wash: `{"r","g","b","a"}` (opaque RGB + wash alpha).
// New color each call; hosts freeze while `speaker` is unchanged. Owned `char*`.
// HANDLE-FREE.
char *ds_random_pastel_wash_json(void);

// Workspace version for About. Owned `char*`. HANDLE-FREE.
char *ds_version(void);

// Startup update check vs GitHub API (blocking HTTP — only network FFI; call off UI
// thread). Compares latest tag to [`crate::VERSION`]. Returns
// `{"update_available", "current_version", "latest_version", "html_url"}`. Any failure
// → `"{}"`; host must treat missing `update_available` as false (never show pill).
// Owned `char*`.
char *ds_update_check_json(void);

// Set active UI locale (BCP-47 / bare tag). NULL no-op; unknown → English at lookup.
// HANDLE-FREE.
void ds_set_locale(const char *locale);

// Active UI locale tag (for matching native number formatters). Owned `char*`. HANDLE-FREE.
char *ds_locale(void);

// Localized string by `key`; missing key returns the key. Owned `char*`. HANDLE-FREE.
char *ds_t(const char *key);

// Localized string with `%{name}` from `args_json` (`{ "name": value }`). Owned `char*`.
// HANDLE-FREE.
char *ds_t_args(const char *key, const char *args_json);

// Hover word for engine lifecycle state. Tokens: running|idle|warming|downloading|
// failed|blocked|missing. `progress` = overall byte-weighted 0..1 (downloading only);
// `why` = failure reason (failed only). Owned `char*`. HANDLE-FREE.
char *ds_engine_state_word(const char *state, double progress, const char *why);

// Lifetime / remaining duration; leading and trailing zero units dropped.
// Owned `char*`. HANDLE-FREE.
char *ds_duration_live(double secs);

// See [`crate::status_fmt::usage_resets_in`]. Owned `char*`.
char *ds_usage_resets_in(int64_t resets_at_unix);

// Runtime label for provider token (mlx|coreml|cuda|cpu; unknown verbatim). Owned
// `char*`. HANDLE-FREE.
char *ds_runtime_label(const char *provider);

// Stat range `"avg{unit}  ·  lo–hi"`. Owned `char*`. HANDLE-FREE.
char *ds_stats_range(double lo, double avg, double hi, uint32_t precision, const char *unit_key);

// Count + audio duration stat. Owned `char*`. HANDLE-FREE.
char *ds_stats_count(uint64_t count, double audio_secs);

// Human file size (decimal SI). Owned `char*`. HANDLE-FREE.
char *ds_human_size(uint64_t bytes);

// Tray kind via [`ds_status::tray_icon_kind`]. `tray_indicator_json`: JSON array of
// [`ds_status::StatusTrayKind`] tokens (NULL/malformed → `[]`). Owned `char*`. HANDLE-FREE.
char *ds_tray_icon_kind(uint8_t stt_active, uint8_t tts_active, const char *tray_indicator_json);

// `ds_tools::DIARIZATION_ENABLED` — single flip for every host. 1 shown / 0 hidden.
// HANDLE-FREE.
uint8_t ds_diarization_ui_enabled(void);

// Session TTS provider: "cpu"|"cuda"|"coreml"|"mlx"|"auto" (NULL/unknown → "auto").
// Restarts the warm helper + resets TTS stats only if the realized provider changes.
// 1 if delivered; new provider/stats via `ds_model_status_json`.
uint8_t ds_set_provider(const char *provider);

// Free a `char*` from any ds_* function. NULL no-op.
void ds_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DONTSPEAK_H */
