/*
 * dontspeak.h — the stable C ABI for ds-core.
 *
 * SwiftUI, WinUI, and GTK hosts all call this same API.
 *
 * The app is an informational menu-bar + health panel, so this surface is
 * intentionally TINY and HANDLE-FREE: a few read-only probes, the in-process
 * engine lifecycle (start/stop/reload), localization, two engine actions
 * (model download, TTS provider), and the string free. ALL config (voice /
 * engine / language / rate / toggles) lives in DontSpeak, NOT here.
 *
 * MEMORY / OWNERSHIP / CONTRACT (read before binding):
 *  - HANDLE-FREE: there is no opaque handle and no create/destroy pair — every
 *    function is free-standing and may be called from any thread (each notes
 *    whether it touches disk / IPC).
 *  - STRINGS: every returned `char*` is heap UTF-8, NUL-terminated, owned by
 *    Rust; free it with ds_string_free() (NEVER libc free()). A returning
 *    function never returns NULL — on any failure it returns an owned empty/`"{}"`
 *    /`"[]"` string you still free. Inbound `const char*` is borrowed for the call
 *    only and copied immediately; NULL is treated as empty / the documented default.
 *  - RETURN CODES: the u8-returning actions return 1 on success and 0 on failure
 *    (engine down, bad input, or a caught panic) — there are no negative error
 *    codes and no out-of-band error channel. Probes return the value directly.
 *  - PANICS: every function catches Rust panics at the boundary and converts them
 *    to the documented default (0, or an owned empty/`"{}"`/`"[]"` string), so a
 *    panic never crosses into C.
 *  - PLATFORM: this ABI is platform-agnostic. Platform specifics (input capture,
 *    key injection, permission prompts) are delegated inside Rust; every host —
 *    macOS, Windows, Linux — calls the same functions in-process.
 *
 * GENERATED by cbindgen from src/ffi.rs — do NOT hand-edit. Run
 * `cargo build -p ds-core --features cbindgen` to regenerate.
 */


#ifndef DONTSPEAK_H
#define DONTSPEAK_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Start the engine on a background thread if not already running. Returns 1 if
// it is now running (started or already up), 0 on failure.
uint8_t ds_engine_start(void);

// Stop the engine (clear the run flag, join the thread). Returns 1 if an engine
// was running, 0 if none. Safe to call on quit.
uint8_t ds_engine_stop(void);

// Ask the running engine to re-read its config (no restart). Returns 1 if an
// engine is running, else 0.
uint8_t ds_engine_reload(void);

// Set global MUTE (the tray "Mute" checkbox). `on != 0` mutes — playback keeps draining,
// only the audio is silenced. Sent to the running engine over IPC (the same channel the
// status read uses); returns 1 if the request was delivered, 0 if the engine is down.
uint8_t ds_set_muted(uint8_t on);

// Open the OS's system-voice settings page (macOS Spoken Content / Windows Speech).
// Returns false on Linux, which has no portable settings page (issue #74).
// Cross-platform seam for the UI "Manage voices" button. Returns 1 if launched, 0 otherwise. HANDLE-FREE.
uint8_t ds_open_voice_settings(void);

// Kokoro (TTS) model set present + valid? (disk probe only). HANDLE-FREE.
uint8_t ds_kokoro_present_global(void);

// Is the FULL Parakeet-ONNX (STT) asset set present + valid? HANDLE-FREE.
uint8_t ds_parakeet_onnx_present_global(void);

// Engine running? (pidfile probe). HANDLE-FREE, safe off main thread.
uint8_t ds_engine_running_global(void);

// The engine's model-status JSON (presence + per-subsystem running map). Owned
// `char*` the caller frees with `ds_string_free`; `"{}"` if the engine is
// down. HANDLE-FREE — safe off the main thread.
char *ds_model_status_json(void);

// Like [`ds_model_status_json`] but BLOCKS until the engine's status sequence
// differs from `since`, or `timeout_ms` elapses — then returns the current status
// JSON (whose `seq` field is the new sequence to pass as `since` next time). This is
// the PUSH transport for the dictation overlay: the UI calls it on a DEDICATED
// background thread (never the UI thread — it blocks) in a loop, re-rendering the
// instant a partial lands instead of polling on a timer. Pass `since = 0` first
// (returns immediately with the current state). Owned `char*`, free with
// `ds_string_free`; `"{}"` if the engine is down.
char *ds_model_status_wait(uint64_t since, uint32_t timeout_ms);

// Weekly/monthly coding-agent quota snapshot. BLOCKING: call off the UI thread.
// `force_refresh != 0` bypasses the 60-second in-process cache. JSON strings are
// owned `char*`, free with `ds_string_free`. HANDLE-FREE — no engine needed.
/* Instant deck: installed agent cards + cached rows. No network.
 * JSON: { cards: [ { agent, account?, rows: [...] } ] } */
char *ds_agent_usage_skeleton_json(void);
/* Blocking single-card load. agent = client token; force_refresh bypasses 60s cache.
 * JSON: { agent, account?, rows: [ { period, used_percent, resets_at_unix } ] } */
char *ds_agent_usage_card_json(const char *agent, uint8_t force_refresh);
/* Aggregate deck refresh (tests/tooling). */
char *ds_agent_usage_json(uint8_t force_refresh);

// The tool catalog for the app's Tools window — a JSON array of
// `{name, description, params:[…]}` with the args as an ORDERED array (the UI form of
// the SAME `ds-tools` catalog the MCP server exposes, so it never drifts from what Claude
// can call). Each param is enriched with a localized `detail` qualifier (enum allowed-values
// or a numeric range) via [`crate::status_fmt::tool_param_detail`], so every host renders
// the SAME pre-built string instead of re-deriving it. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine.
char *ds_tools_json(void);

// The third-party libraries catalog for the app's Libraries window — a JSON array of
// `{name, usage, homepage, license, license_url, files:[{name, url, size_bytes?}]}`,
// collected from the SAME download registry every platform fetches from (so the credits
// can't drift from what's actually shipped). Scope is the downloaded models + runtime.
// Owned `char*`, free with `ds_string_free`. HANDLE-FREE — no engine.
char *ds_libraries_json(void);

// The COMBINED activity-log tail for the app's Logs tab — a JSON array of
// `{source, level, text}` merging the unified log (each line tagged engine/tts/stt/caps/hook/
// mcp/config) with every sibling auxiliary log (e.g. the out-of-process `helper` stderr), in
// rough chronological order. `max_bytes` caps the tail PER file. Opens SHARED-read (works while
// the engine appends); the UI derives its source filter from the distinct `source` values.
// "[]" when there's no log yet. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_logs_json(uint32_t max_bytes);

// Like [`ds_logs_json`] but BLOCKS until the logs directory changes (any `*.log` file
// created/modified/removed — the unified log or a sibling aux log; rotated `*.log.N` files
// don't count) or `timeout_ms` elapses, then returns the CURRENT combined log JSON — the SAME
// shape `ds_logs_json` returns, no diff/since token (unlike `ds_model_status_wait`, there's no
// cross-call sequence to echo back — the caller just re-renders the full tail each time). This
// is CLIENT-SIDE (an fs watch in the calling process), NOT an engine-IPC round-trip like the
// status wait — logs are read straight off disk here, same as `ds_logs_json`. Call ONLY on a
// DEDICATED background thread (it blocks up to `timeout_ms`), in a loop: call → render → call
// again. `max_bytes` caps the tail PER file, same as `ds_logs_json`. Owned `char*`, free with
// `ds_string_free`; `"[]"` if `Paths` can't resolve. HANDLE-FREE.
char *ds_logs_wait(uint32_t max_bytes, uint32_t timeout_ms);

// Erase the ENTIRE on-disk activity log — the unified log, its rotated backups, and every
// sibling auxiliary log — for the Logs tab's Clear button. Irreversible; the caller must confirm
// with the user before calling. A no-op (not an error) if there's nothing on disk yet.
// HANDLE-FREE — no engine.
void ds_logs_clear(void);

// The product homepage URL (e.g. the About screen's clickable link) — a single
// source of truth so every platform's UI opens the same address. Owned `char*`,
// free with `ds_string_free`. HANDLE-FREE — no engine needed.
char *ds_homepage_url(void);

// Brand colors (hex sRGB) as a JSON object — the single cross-platform source of truth so
// macOS + Windows render identical tints (the visual analogue of the shared ds-i18n
// string catalog). Keys: `seed_purple`, `mic_orange`, `warning`. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine needed.
char *ds_brand_colors_json(void);

// Logs-tab colors as a JSON object (`{levels:{ERROR,WARN}, source_palette:[…]}`) — the single
// cross-platform source of truth for the activity-log view's coloring, so every platform's Logs
// tab tints identically (sibling of `ds_brand_colors_json`). Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine.
char *ds_log_colors_json(void);

// One random Usage speaking-card pastel wash as JSON `{"r","g","b","a"}` (opaque sRGB +
// wash alpha). Single recipe in ds-core (HSV random H, fixed S/V); hosts only paint and freeze
// while tts_source is unchanged. New color each call. Owned `char*`, free with `ds_string_free`.
// HANDLE-FREE — no engine. On failure returns "{}" (host skips wash).
char *ds_random_pastel_wash_json(void);

// The product version (the Rust workspace version) for the About screen — one
// shared source for every platform's UI. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE — no engine needed.
char *ds_version(void);

// Startup update check: is a newer DontSpeak release out? Hits the real GitHub API (a
// blocking HTTP GET — this is the one FFI call that touches the network, NOT handle-free the
// way the disk/IPC-only probes above are; call it off the UI thread, e.g. once at startup on
// a background thread) and compares the latest release tag against [`crate::VERSION`] via
// [`ds_model::update_check::check_for_update_at`]. Returns a JSON object:
// `{"update_available":bool,"current_version":str,"latest_version":str,"html_url":str}` — the
// per-host UI reads `update_available` to decide whether to show the pill next to the version
// number, `latest_version` as the version it displays, and `html_url` as the pill's own
// click-through target. On ANY failure (offline, rate-limited, malformed response) returns
// `"{}"` — a host must treat a missing `update_available` key the same as `false`, never as
// "unknown, so show the pill anyway". Owned `char*`, free with `ds_string_free`.
char *ds_update_check_json(void);

// Set the active UI locale (BCP-47 or a bare language tag, e.g. "de"). NULL is a no-op.
// Unknown locales fall back to English at lookup. HANDLE-FREE — no engine needed.
void ds_set_locale(const char *locale);

// The active UI locale tag — so a UI can match its native number formatter to the
// catalog's language. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_locale(void);

// Look up a localized UI string by `key` (a C string). English fallback; a missing key
// returns the key itself. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_t(const char *key);

// Look up a localized string and interpolate `%{name}` placeholders from `args_json`, a
// JSON object `{ "name": value }` (values stringified). Both args are C strings. Owned
// `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_t_args(const char *key, const char *args_json);

// Localized hover word for an engine lifecycle state. `state` is the model-status token from
// the canonical [`ds_status::EngineState`] vocabulary ("running"|"idle"|"warming"|
// "downloading"|"failed"|"blocked"|"missing"),
// `progress` the 0..1 OVERALL download fraction — byte-weighted across the whole model set, a
// single global percent (only used for "downloading"), `why` the
// failure reason (only used for "failed"; empty → the generic default). Owned `char*`,
// free with `ds_string_free`. HANDLE-FREE. The ONE state→word formatter shared by every UI.
char *ds_engine_state_word(const char *state, double progress, const char *why);

// Localized duration; leading+trailing zero units dropped (e.g. "12m 04s", "1d 05h").
// Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_duration_live(double secs);

// Usage remaining duration from UTC epoch (e.g. "2d 05h"). Owned `char*`.
char *ds_usage_resets_in(int64_t resets_at_unix);

// Localized RUNTIME label for a resolved provider token ("ane"|"coreml"|"cuda"|
// "cpu"; unknown passes through). The TTS/STT runtime detail. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE.
char *ds_runtime_label(const char *provider);

// A stat RANGE string — "avg`<unit>`  ·  lo–hi". `precision` = decimals; `unit_key` = the
// catalog key for the trailing unit ("status.stats.unit.times" / ".seconds"). Owned `char*`,
// free with `ds_string_free`. HANDLE-FREE.
char *ds_stats_range(double lo, double avg, double hi, uint32_t precision, const char *unit_key);

// A COUNT + audio-duration stat string — "`<count>`  <audio_secs> s". Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE.
char *ds_stats_count(uint64_t count, double audio_secs);

// A human-readable file size — decimal units, "1.4 GB" / "325 MB" / "12 KB" / "512 B". The ONE
// size formatter shared by every UI's Libraries/Credits tab. Owned `char*`, free with
// `ds_string_free`. HANDLE-FREE.
char *ds_human_size(uint64_t bytes);

// Tray / state-stripe kind: "idle" | "recording" | "speaking". `stt_active` / `tts_active`
// are non-zero when Caps dictation / TTS playback is live. `tray_indicator_json` is the
// model_status `tray_indicator` JSON string array (NULL/malformed → []). Owned `char*`, free
// with `ds_string_free`. HANDLE-FREE. ONE mapping shared by every host.
char *ds_tray_icon_kind(uint8_t stt_active, uint8_t tts_active, const char *tray_indicator_json);

// Active TTS model_status object key for config token `tts_engine`: "kokoro" | "tts_system" |
// "" when off/unknown. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_active_tts_slot(const char *tts_engine);

// Active STT model_status object key for config token `stt_engine`: "parakeet" | "claude_code" |
// "system" | "" when off/unknown. Owned `char*`, free with `ds_string_free`. HANDLE-FREE.
char *ds_active_stt_slot(const char *stt_engine);

// Whether diarization UI/tools are shipped (`ds_tools::DIARIZATION_ENABLED`). ONE flip for
// every host. Returns 1 when shown, 0 when hidden. HANDLE-FREE.
uint8_t ds_diarization_ui_enabled(void);

// Set the TTS execution provider for this session: `provider` is "cpu" | "cuda" |
// "coreml" | "ane" | "auto" (NULL/unknown → "auto"). The engine restarts the warm Kokoro child on
// the new provider and resets its TTS stats (only if the active provider actually
// changed). Returns 1 if the request reached the engine, else 0. The new provider
// + fresh stats then show up via `ds_model_status_json`.
uint8_t ds_set_provider(const char *provider);

// Free a `char*` returned by any ds_* function. NULL is a no-op.
void ds_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DONTSPEAK_H */
